# Generated by Django 3.1.7 on 2021-12-06 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipam', '0043_add_tenancy_to_aggregates'),
        ('dcim', '0122_standardize_name_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AciAp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AciTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='fvRsPathAtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('pod_id', models.PositiveIntegerField()),
                ('leafs_id', models.PositiveIntegerField()),
                ('ap', models.CharField(max_length=64)),
                ('epg', models.CharField(max_length=64)),
                ('interface', models.CharField(max_length=64)),
                ('change_ref', models.CharField(max_length=64)),
                ('bob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plugin_fvRsPathAtt.aciap')),
                ('encap_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipam.vlan')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AciEpg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('aci_ap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plugin_fvRsPathAtt.aciap')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aciap',
            name='aci_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plugin_fvRsPathAtt.acitenant'),
        ),
    ]
