# Generated by Django 3.1.7 on 2021-12-06 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0043_add_tenancy_to_aggregates'),
        ('dcim', '0122_standardize_name_length'),
        ('plugin_fvRsPathAtt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fvrspathatt',
            name='encap_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipam.vlan'),
        ),
        migrations.AlterField(
            model_name='fvrspathatt',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.site'),
        ),
    ]
